//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ÊÓÆµ±à½âÂëÆ÷.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MYTYPE                      129
#define IDI_ICON1                       131
#define IDD_EncodeDlg                   133
#define IDD_DecodeDlg                   134
#define IDB_car                         136
#define IDD_RateControl                 142
#define IDD_Motion                      143
#define IDD_GENCODEBOOK                 146
#define IDI_ICON2                       147
#define IDD_WatmarDlg                   149
#define IDD_CALCULATENC                 151
#define IDD_CALCULATENC2                154
#define IDD_ATTACK                      155
#define IDI_ICON3                       157
#define IDD_DIALOG1                     158
#define IDD_NCVIEW                      158
#define IDI_ICON4                       159
#define IDD_IMPROATTACK                 160
#define IDC_InType                      1001
#define IDC_InitDir                     1002
#define IDC_Browse                      1003
#define IDC_MaxFrame                    1004
#define IDC_QPI                         1005
#define IDC_QP                          1006
#define IDC_CHECK1                      1007
#define IDC_Pnum                        1008
#define IDC_IfRateControl               1009
#define IDC_RADIO1                      1010
#define IDC_RADIO2                      1011
#define IDC_Bitrate                     1012
#define IDC_frame10                     1018
#define IDC_frame25                     1019
#define IDC_frame30                     1020
#define IDC_VQ                          1021
#define IDC_OPENBOOK                    1022
#define IDC_BOOKNAME                    1023
#define IDC_EDIT1                       1024
#define IDC_BUTTON1                     1025
#define IDC_VQ2                         1025
#define IDC_BOOKGENERATE                1026
#define IDC_BUTTON2                     1026
#define IDC_Visualbook                  1027
#define IDC_EDIT6                       1027
#define IDC_BARDO                       1029
#define IDC_CHECK2                      1030
#define IDC_Recoed                      1030
#define ID_OPENKEY                      1032
#define IDC_RADIO3                      1046
#define IDC_HIGHERROR                   1046
#define IDC_MB                          1046
#define IDC_NOISE                       1046
#define IDC_Multip                      1047
#define IDC_EDIT2                       1048
#define IDC_2ndwatermark                1049
#define IDC_EDIT7                       1049
#define IDC_EDIT3                       1050
#define IDC_EDIT4                       1051
#define IDC_EDIT5                       1052
#define IDC_EDIT8                       1053
#define IDC_EDIT9                       1054
#define IDC_EDIT10                      1055
#define IDC_COMBO2                      1059
#define IDC_ATTACKOPEN                  1060
#define IDC_MINERROR                    1061
#define IDC_MIDERROR                    1062
#define ID_OK                           1063
#define IDC_HTTP                        1064
#define IDC_BASIC                       1067
#define IDC_GEN                         1068
#define IDC_WMCBGEN                     1069
#define IDC_BUTTON3                     1072
#define IDC_TotalFrame                  1075
#define IDC_WMS                         1076
#define ID_NCvalues                     1077
#define IDC_NCLIST1                     1078
#define IDC_SCROLLBAR1                  1081
#define IDC_OPENYUV                     1082
#define IDC_SLIDER1                     1083
#define IDC_PROGRESS1                   1084
#define IDC_COMBO1                      1085
#define IDC_ROTATE                      1087
#define IDC_BLUR                        1089
#define IDC_CROP                        1090
#define IDC_FILTER                      1091
#define IDC_ATTACK                      1092
#define IDC_TEXT                        1093
#define IDC_CANCEL                      1094
#define ID_Encode                       32771
#define ID_Decode                       32772
#define ID_GENERATE                     32780
#define ID_DECODEVQ                     32781
#define ID_VISUALDEC                    32782
#define ID_MENUITEM32783                32783
#define ID_MVDM                         32784
#define ID_MultiExtract                 32785
#define ID_MENUITEM32786                32786
#define ID_DCTPARITY                    32787
#define ID_SAVWMARK                     32788
#define ID_SAVEMULTIMARK                32792
#define ID_RFWM                         32793
#define ID_2NC                          32797
#define ID_BITERROR                     32798
#define ID_NORMALPLAY                   32800
#define ID_FASTPLAY                     32801
#define ID_SLOWPLAY                     32802
#define ID_RECORD                       32808
#define ID_BUTTON32810                  32810
#define ID_PAUSE                        32810
#define ID_BRIDGEEXTRACT                32811
#define ID_ROBSEMIFRGWM                 32813
#define ID_TRIMARK                      32814
#define ID_RFVIEW                       32815
#define ID_MENUITEM32818                32818

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32819
#define _APS_NEXT_CONTROL_VALUE         1095
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
